{
 "title": "EDSM",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total Jumps",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "jump",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Distance Traveled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "jump",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Federation Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rank",
     "query": "SELECT * FROM \"rank\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activity", "operator": "=", "value": "Federation" }
     ]
    }
   ]
  },
  {
   "title": "Jumps By Star Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_primaryStarType",
     "groupBy": [
      { "params": [ "primaryStarType" ], "type": "tag" }
     ],
     "measurement": "jump",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Jump Distance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jump",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest Jump",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "jump",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Empire Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rank",
     "query": "SELECT * FROM \"rank\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activity", "operator": "=", "value": "Empire" }
     ]
    }
   ]
  },
  {
   "title": "Combat Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rank",
     "query": "SELECT * FROM \"rank\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activity", "operator": "=", "value": "Combat" }
     ]
    }
   ]
  },
  {
   "title": "Trade Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rank",
     "query": "SELECT * FROM \"rank\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activity", "operator": "=", "value": "Trade" }
     ]
    }
   ]
  },
  {
   "title": "Exploration Rank",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rank",
     "query": "SELECT * FROM \"rank\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activity", "operator": "=", "value": "Explore" }
     ]
    }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Credits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "credits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Jumps",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "jump",
     "select": [
      [
       { "params": [ "system" ], "type": "field" }
      ],
      [
       { "params": [ "primaryStarType" ], "type": "field" }
      ],
      [
       { "params": [ "distance" ], "type": "field" }
      ],
      [
       { "params": [ "firstDiscover" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}