{
 "title": "Exist.io",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Daily Tags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_tag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "custom",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Insights",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "insight",
     "select": [
      [
       { "params": [ "html" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mood",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Mood",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mood",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}