{
 "title": "Fitbit",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Daily Steps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "measurement": "steps",
     "query": "SELECT \"value\" FROM \"steps\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps Taken",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Weight",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Weight (LBS)" }
   ],
   "targets": [
    {
     "alias": "Weight",
     "measurement": "weight",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "BMI",
     "measurement": "bmi",
     "query": "SELECT \"bmi\" FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Body Fat",
     "measurement": "fat",
     "query": "SELECT \"bmi\" FROM \"weight\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Floors Climbed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "floors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Calorie Burn",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "calories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance Walked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "distance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "deviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "m", "label": "Duration" }
   ],
   "targets": [
    {
     "alias": "Deep",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_deep" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Light",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "REM",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_rem" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Awake",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_wake" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Resting Heart Rate",
     "measurement": "restingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Time",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sedentary",
     "measurement": "minutesSedentary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Lightly Active",
     "measurement": "minutesLightlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Fairly Active",
     "measurement": "minutesFairlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Very Active",
     "measurement": "minutesVeryActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "* 60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate Zones",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "m", "label": "Duration" }
   ],
   "targets": [
    {
     "alias": "Fat Burn",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Fat Burn" }
     ]
    },
    {
     "alias": "Cardio",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Cardio" }
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Peak" }
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "BPM" }
   ],
   "targets": [
    {
     "alias": "Heart Rate (BPM)",
     "measurement": "heartrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}