{
 "title": "Foursquare",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "type": "grafana-map-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "venue_name" ], "type": "tag" }
     ],
     "measurement": "checkin",
     "query": "SELECT \"venue_name\", \"latitude\", \"longitude\" FROM \"checkin\" WHERE $timeFilter GROUP BY \"venue_id\"",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checkins",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "checkin",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Mayorships",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "checkin",
     "query": "SELECT last(\"latitude\"),\"venue_name\", \"category\" FROM \"checkin\" WHERE (\"mayor\" = 'True') GROUP BY \"venue_id\"",
     "select": [
      [
       { "params": [ "venue_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "mayor", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Top Locations",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT venue_name as Location,category as Category,top(count,10) as Visits FROM (SELECT count(\"latitude\") AS count FROM \"checkin\" WHERE $timeFilter GROUP BY \"venue_id\",\"venue_name\",\"category\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location Categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_category",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "checkin",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Places Visited",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "venue_name" ], "type": "field" }
     ],
     "measurement": "checkin",
     "query": "SELECT count(\"venue_id\") FROM (SELECT last(\"latitude\") FROM \"checkin\" WHERE $timeFilter GROUP BY \"venue_id\")",
     "select": [
      [
       { "params": [ "venue_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cities Visited",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "venue_name" ], "type": "field" }
     ],
     "measurement": "checkin",
     "query": "SELECT count(\"city\") FROM (SELECT last(\"latitude\") FROM \"checkin\" WHERE $timeFilter GROUP BY \"city\")",
     "select": [
      [
       { "params": [ "venue_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "States Visited",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "venue_name" ], "type": "field" }
     ],
     "measurement": "checkin",
     "query": "SELECT count(\"state\") FROM (SELECT last(\"latitude\") FROM \"checkin\" WHERE (\"country\" = 'United States') AND $timeFilter GROUP BY \"state\")",
     "select": [
      [
       { "params": [ "venue_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Countries Visited",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "venue_id" ], "type": "tag" },
      { "params": [ "venue_name" ], "type": "field" }
     ],
     "measurement": "checkin",
     "query": "SELECT count(\"country\") FROM (SELECT last(\"latitude\") FROM \"checkin\" WHERE $timeFilter GROUP BY \"country\")",
     "select": [
      [
       { "params": [ "venue_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}