{
 "title": "Gaming",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Most Played Games",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_title",
     "groupBy": [
      { "params": [ "title" ], "type": "tag" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Time Per Platform",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_platform",
     "groupBy": [
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Achievements Per Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Steam",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "achievement",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "Steam" }
     ]
    },
    {
     "alias": "Xbox Live",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "achievement",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "Xbox Live" }
     ]
    },
    {
     "alias": "Google Play",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "achievement",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "platform", "operator": "=", "value": "Google Play" }
     ]
    }
   ]
  },
  {
   "title": "Recent Games",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "time",
     "query": "SELECT last(\"value\") AS \"value\" FROM \"time\" WHERE $timeFilter GROUP BY time(1d),\"title\",\"platform\" fill(none) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recent Achievements",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "measurement": "achievement",
     "select": [
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "description" ], "type": "field" }
      ],
      [
       { "params": [ "platform" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}