{
 "title": "RescueTime",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "RescueTime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Productive Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "productivity", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Top Activities",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(s,10),activity FROM (SELECT sum(\"duration\") as s FROM \"activity\" WHERE $timeFilter GROUP BY \"activity\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_category",
     "groupBy": [
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "activity",
     "query": "SELECT \"duration\" FROM \"activity\" WHERE $timeFilter DESC GROUP BY \"category\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distracting Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "productivity", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Productivity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "Productivity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "activity",
     "query": "SELECT sum(duration_productivity) FROM (SELECT \"duration\" * \"productivity\" FROM \"activity\" WHERE $timeFilter) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "productivity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Productive vs. Distracting Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "Productive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activity",
     "query": "SELECT sum(duration_productivity) FROM (SELECT \"duration\" * \"productivity\" FROM \"activity\" WHERE $timeFilter AND \"productivity\" >= 0) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "productivity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "productivity", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Distracting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "activity",
     "query": "SELECT sum(duration_productivity) FROM (SELECT \"duration\" * \"productivity\" FROM \"activity\" WHERE $timeFilter AND \"productivity\" <= 0) GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "productivity" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "productivity", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Top Productive Activities",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT activity,category,top(s,25) FROM (SELECT sum(\"duration\") as s FROM \"activity\" WHERE $timeFilter AND productivity > 0 GROUP BY \"activity\",\"category\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Distracting Activities",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT activity,category,top(s,25) FROM (SELECT sum(\"duration\") as s FROM \"activity\" WHERE $timeFilter AND productivity < 0 GROUP BY \"activity\",\"category\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}